// Generated by Wrangler by running `wrangler types`

interface Env {
	WORKER_ENV: "production" | "local";
	FRONTEND_ORIGIN: "https://spaced2.pages.dev/" | "http://localhost:5173";
	COOKIE_SECRET: string;
	RESEND_API_KEY: string;
	FILES_BUCKET: R2Bucket; 
	D1: D1Database;
	GOOGLE_CLIENT_ID: string;
}

declare module 'cloudflare:test' {
	// eslint-disable-next-line @typescript-eslint/no-empty-object-type
	interface ProvidedEnv extends Env {}
}
