// Generated by Wrangler by running `wrangler types`

interface Env {
	D1: D1Database;
	COOKIE_SECRET: string;
	WORKER_ENV: 'production' | 'local';
}

declare module 'cloudflare:test' {
	interface ProvidedEnv extends Env {}
}
