// AUTOGENERATED - DO NOT EDIT: Used for testing
export const schemaString = `
CREATE TABLE \`card_bookmarked\` (
	\`card_id\` text PRIMARY KEY NOT NULL,
	\`bookmarked\` integer DEFAULT false NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`seq_no\` integer NOT NULL,
	\`last_modified_client\` text NOT NULL,
	FOREIGN KEY (\`card_id\`) REFERENCES \`cards\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`last_modified_client\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`card_bookmarked_card_id_idx\` ON \`card_bookmarked\` (\`card_id\`);--> statement-breakpoint
CREATE INDEX \`card_bookmarked_card_id_seq_no_modified_client_idx\` ON \`card_bookmarked\` (\`card_id\`,\`seq_no\`,\`last_modified_client\`);--> statement-breakpoint
CREATE TABLE \`card_contents\` (
	\`card_id\` text PRIMARY KEY NOT NULL,
	\`front\` text NOT NULL,
	\`back\` text NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`seq_no\` integer NOT NULL,
	\`last_modified_client\` text NOT NULL,
	FOREIGN KEY (\`card_id\`) REFERENCES \`cards\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`last_modified_client\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`card_contents_card_id_idx\` ON \`card_contents\` (\`card_id\`);--> statement-breakpoint
CREATE INDEX \`card_contents_card_id_seq_no_modified_client_idx\` ON \`card_contents\` (\`card_id\`,\`seq_no\`,\`last_modified_client\`);--> statement-breakpoint
CREATE TABLE \`card_decks\` (
	\`card_id\` text NOT NULL,
	\`deck_id\` text NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`seq_no\` integer NOT NULL,
	\`cl_count\` integer DEFAULT 0 NOT NULL,
	\`last_modified_client\` text NOT NULL,
	PRIMARY KEY(\`card_id\`, \`deck_id\`),
	FOREIGN KEY (\`card_id\`) REFERENCES \`cards\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`deck_id\`) REFERENCES \`decks\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`last_modified_client\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`card_decks_card_id_idx\` ON \`card_decks\` (\`card_id\`);--> statement-breakpoint
CREATE INDEX \`card_decks_deck_id_idx\` ON \`card_decks\` (\`deck_id\`);--> statement-breakpoint
CREATE INDEX \`card_decks_card_id_deck_id_seq_no_modified_client_idx\` ON \`card_decks\` (\`deck_id\`,\`card_id\`,\`seq_no\`,\`last_modified_client\`);--> statement-breakpoint
CREATE TABLE \`card_deleted\` (
	\`card_id\` text PRIMARY KEY NOT NULL,
	\`deleted\` integer DEFAULT true NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`seq_no\` integer NOT NULL,
	\`last_modified_client\` text NOT NULL,
	FOREIGN KEY (\`card_id\`) REFERENCES \`cards\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`last_modified_client\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`card_deleted_card_id_idx\` ON \`card_deleted\` (\`card_id\`);--> statement-breakpoint
CREATE INDEX \`card_deleted_card_id_seq_no_modified_client_idx\` ON \`card_deleted\` (\`card_id\`,\`seq_no\`,\`last_modified_client\`);--> statement-breakpoint
CREATE TABLE \`card_suspended\` (
	\`card_id\` text PRIMARY KEY NOT NULL,
	\`suspended\` integer DEFAULT (current_timestamp) NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`seq_no\` integer NOT NULL,
	\`last_modified_client\` text NOT NULL,
	FOREIGN KEY (\`card_id\`) REFERENCES \`cards\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`last_modified_client\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`card_suspended_card_id_idx\` ON \`card_suspended\` (\`card_id\`);--> statement-breakpoint
CREATE INDEX \`card_suspended_card_id_seq_no_modified_client_idx\` ON \`card_suspended\` (\`card_id\`,\`seq_no\`,\`last_modified_client\`);--> statement-breakpoint
CREATE TABLE \`cards\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`seq_no\` integer NOT NULL,
	\`user_id\` text NOT NULL,
	\`last_modified_client\` text NOT NULL,
	\`due\` integer DEFAULT (current_timestamp) NOT NULL,
	\`stability\` real NOT NULL,
	\`difficulty\` real NOT NULL,
	\`elapsed_days\` integer NOT NULL,
	\`scheduled_days\` integer NOT NULL,
	\`reps\` integer NOT NULL,
	\`lapses\` integer NOT NULL,
	\`state\` text NOT NULL,
	\`last_review\` integer,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`last_modified_client\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`cards_user_id_idx\` ON \`cards\` (\`user_id\`);--> statement-breakpoint
CREATE INDEX \`cards_user_id_seq_no_modified_client_idx\` ON \`cards\` (\`user_id\`,\`seq_no\`,\`last_modified_client\`);--> statement-breakpoint
CREATE TABLE \`clients\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`user_id\` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`clients_user_id_idx\` ON \`clients\` (\`user_id\`,\`id\`);--> statement-breakpoint
CREATE TABLE \`decks\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text NOT NULL,
	\`description\` text NOT NULL,
	\`deleted\` integer DEFAULT false NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`seq_no\` integer NOT NULL,
	\`user_id\` text NOT NULL,
	\`last_modified_client\` text NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`last_modified_client\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`decks_user_id_idx\` ON \`decks\` (\`user_id\`);--> statement-breakpoint
CREATE INDEX \`decks_user_id_seq_no_modified_client_idx\` ON \`decks\` (\`user_id\`,\`seq_no\`,\`last_modified_client\`);--> statement-breakpoint
CREATE TABLE \`review_log_deleted\` (
	\`review_log_id\` text PRIMARY KEY NOT NULL,
	\`deleted\` integer DEFAULT false NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`seq_no\` integer NOT NULL,
	\`last_modified_client\` text NOT NULL,
	FOREIGN KEY (\`review_log_id\`) REFERENCES \`review_logs\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`last_modified_client\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`review_log_deleted_review_log_id_idx\` ON \`review_log_deleted\` (\`review_log_id\`);--> statement-breakpoint
CREATE INDEX \`review_log_deleted_review_log_id_seq_no_modified_client_idx\` ON \`review_log_deleted\` (\`review_log_id\`,\`seq_no\`,\`last_modified_client\`);--> statement-breakpoint
CREATE TABLE \`review_logs\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`card_id\` text NOT NULL,
	\`seq_no\` integer NOT NULL,
	\`last_modified_client\` text NOT NULL,
	\`grade\` text NOT NULL,
	\`state\` text NOT NULL,
	\`due\` integer NOT NULL,
	\`stability\` real NOT NULL,
	\`difficulty\` real NOT NULL,
	\`elapsed_days\` integer NOT NULL,
	\`last_elapsed_days\` integer NOT NULL,
	\`scheduled_days\` integer NOT NULL,
	\`review\` integer NOT NULL,
	\`duration\` integer DEFAULT 0 NOT NULL,
	\`created_at\` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (\`last_modified_client\`) REFERENCES \`clients\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`review_logs_card_id_idx\` ON \`review_logs\` (\`card_id\`);--> statement-breakpoint
CREATE INDEX \`review_logs_card_id_seq_no_modified_client_idx\` ON \`review_logs\` (\`card_id\`,\`seq_no\`,\`last_modified_client\`);--> statement-breakpoint
CREATE TABLE \`sessions\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`user_id\` text NOT NULL,
	\`valid\` integer DEFAULT true NOT NULL,
	\`created_at\` integer DEFAULT (current_timestamp) NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`last_active_at\` integer DEFAULT (current_timestamp) NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX \`sessions_user_id_idx\` ON \`sessions\` (\`user_id\`);--> statement-breakpoint
CREATE TABLE \`users\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`last_modified\` integer DEFAULT (current_timestamp) NOT NULL,
	\`email\` text NOT NULL,
	\`is_active\` integer DEFAULT true NOT NULL,
	\`password_hash\` text NOT NULL,
	\`next_seq_no\` integer DEFAULT 1 NOT NULL,
	\`failed_login_attempts\` integer DEFAULT 0 NOT NULL,
	\`password_reset_token\` text,
	\`password_reset_token_expires_at\` integer
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`users_email_idx\` ON \`users\` (\`email\`);;
CREATE TABLE \`oauth_accounts\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`user_id\` text NOT NULL,
	\`provider\` text NOT NULL,
	\`provider_user_id\` text NOT NULL,
	\`created_at\` integer DEFAULT (current_timestamp) NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`oauth_accounts_provider_provider_user_id_idx\` ON \`oauth_accounts\` (\`provider\`,\`provider_user_id\`);--> statement-breakpoint
ALTER TABLE \`users\` ADD \`image_url\` text;--> statement-breakpoint
ALTER TABLE \`users\` ADD \`display_name\` text;;
`;
